version: '3'
services: 
  client: 
    image: client
    build: ./client/
    ports:
      - "3000:3000"
    networks:
      - myDockerApp
  api:
    image: api
    build: ./server/
    ports:
        - "5000:5000"
    networks:
      - myDockerApp
    environment:
      #we use this inside app.js 
      - MONGO_DB_APP=mongodb://mongo:27017/monoAppDB 
  mongo: 
    image: mongo 
    ports: 
      - "27017:27017"
    networks: 
      - myDockerApp
  nginx: 
    build: ./client/
    ports: 
      - "80:80"
    networks: 
      - myDockerApp
networks: 
  myDockerApp:
    #
    driver: bridge