version: '3'
services: 
  client: 
    image: client
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - monoCI
  api:
    image: api
    build: ./server/
    ports:
        - "5000:5000"
    networks:
      - monoCI
    environment:
      - MONGO_DB_APP=mongodb://mongo:27017/monoAppDB 
  mongo: 
    image: mongo 
    ports: 
      - "27017:27017"
    networks: 
      - monoCI
  nginx: 
    build: ./client/
    ports: 
      - "80:80"
    networks: 
      - monoCI
networks: 
  monoCI:
      driver: bridge